### PR TITLE
Implement an iterator for Ipv4Network

### PR DESCRIPTION
**Pull request by achanda**
@faern please take a look

### CODE REVIEW

**Comment by faern** [comment]
I think it would be cleaner if you used `nth` inside of `next` instead of manually computing the next address. Then you can simplify `curr: Ipv4Addr` to `curr: u64`:

```rust
fn next(&mut self) -> Option<Ipv4Addr> {
    let n = self.curr;
    self.curr += 1;
    self.network.nth(n as u32)
}
```

However, this would wrap to the start after the last address in a `/0` network. So some more error checking is necessary.

**Comment by faern** [comment]
I would also do a little bit more extensive testing. The current test would pass if there were no addresses returned, all addresses equal etc.

```rust
    #[test]
    fn iterator_v4() {
        let cidr = Ipv4Network::from_cidr("192.168.122.0/29").unwrap();
        let all_addrs = cidr.iter().collect::<Vec<Ipv4Addr>>();
        assert_eq!(8, all_addrs.len());
        assert_eq!(Ipv4Addr::new(192, 168, 122, 0), all_addrs[0]);
        assert_eq!(Ipv4Addr::new(192, 168, 122, 7), all_addrs[7]);
        for addr in all_addrs.into_iter() {
            assert!(cidr.contains(addr));
        }
    }
```

**Comment by faern** [comment]
In the end my suggestion didn't end up with less code. I thought using `nth` would greatly reduce the complexity, but the problem around `/0` networks made it more complex. I'm too tired to think clearly about this at the moment. If you can find something even better that would be great.

Your current solution has two problems: 
* It starts at the second address not the first:
  
  ```rust
  #[test]
      fn iterator_v4_first() {
          let cidr = Ipv4Network::from_cidr("0/0").unwrap();
          let mut iter = cidr.iter();
          assert_eq!(Ipv4Addr::new(0,0,0,0), iter.next().unwrap());
      }
  ```
* It loops and never ends on a `/0` network:

  ```rust
    #[test]
    fn iterator_v4_huge() {
        let cidr = Ipv4Network::from_cidr("0/0").unwrap();
        let mut iter = cidr.iter();
        for i in 0..u32::max_value() {
            assert!(iter.next().is_some());
        }
        assert!(iter.next().is_none());
    }
  ```
  Well, it gives an arithmetic overflow in debugging builds, but should wrap in release builds.

**Comment by faern** [comment]
I did some benchmarking since both our solutions are more complex than they need to be. With this benchmark:

```rust
    #[bench]
    fn bench_v4_iterator(b: &mut Bencher) {
        let cidr = Ipv4Network::from_cidr("0/10").unwrap();
        let mut iter = cidr.iter();
        b.iter(|| {
            while let Some(n) = iter.next() {
                test::black_box(n);
            }
        });
    }
```

* Your current solution: `9,213,490 ns/iter`
* My proposed solution using `nth`: `12,378,623 ns/iter`

A very much simpler implementation:
```rust
    pub struct Ipv4NetworkIterator {
        curr: u64,
        end: u64,
    }

    pub fn iter(&self) -> Ipv4NetworkIterator {
        let (_, start) = self.network();
        let end = start as u64 + self.size();
        Ipv4NetworkIterator {
            curr: start as u64,
            end: end,
        }
    }

    fn next(&mut self) -> Option<Ipv4Addr> {
        if self.curr < self.end {
            let result = Ipv4Addr::from(self.curr as u32);
            self.curr += 1;
            Some(result)
        } else {
            None
        }
    }
```

Gives benchmark results: `74,415 ns/iter`. Approximately a factor 100 faster :smile:

**Comment by achanda** [comment]
@faern that's a great find 😄 Please feel free to start another PR with this approach. It might be nice to have the benchmark as well.

**Comment by faern** [comment]
@achanda Including the benchmark will only make it build on unstable so I will leave that out. But I will start a new PR with new implementation and more extensive tests from above.

**Pull request closed without merging**
