### PR TITLE
Implement useful traits on the Ip*Network structs

### PR DESCRIPTION
**Pull request by faern**
I wanted to be able to easily clone the structs. Seems reasonable?

### CODE REVIEW

**Comment by achanda** [comment]
Sounds good. While you're at it, mind adding `Copy` and `Hash` too?

**Comment by faern** [comment]
`Debug` is already manuall implemented for those types. I'll add the rest. I'll also add `Eq` and `PartialEq` so it's possible to store them as keys in hashmaps.

**Comment by faern** [comment]
I will be away for one week now, so I won't work on this PR for a while if you want something more changed.

**Comment by achanda** [comment]
Looks perfect, thanks!

**Pull request merged**
