### PR TITLE
Add a deprecation note to NetworkSize

### PR DESCRIPTION
**Pull request by achanda**
https://github.com/achanda/ipnetwork/issues/102
cc @lucab @vorner

### CODE REVIEW

**Comment by achanda** [comment]
Leaving this open for a while so that anyone gets a chance to comment.

**Comment by lucab** [comment]
I'm not using this interface (and I'm actually happy with the current API), but maybe you'd want to first land the new methods and then deprecate this? Or is your plan to re-use the same exact function name?

**Comment by achanda** [comment]
I was hoping to use the same names, so planning to:
1. Merge this PR
2. Cut a release
3. Merge another PR to change the API
4. Cut a new release

**Comment by achanda** [comment]
I think I should take a step back to figure out a best way to deprecate these. I will close this one and get back to this when I have a plan.

**Pull request closed without merging**
